version: '3.8'

services:
  siteproxy:
    image: node:18
    container_name: siteproxy-node
    restart: unless-stopped
    ports:
      - 5006:5006
    volumes:
      - ./../:/home/node/siteproxy/
    working_dir: /home/node/siteproxy/
    entrypoint: ["/bin/sh","/home/node/siteproxy/start.sh"]
    environment:
      - HTTP_PROXY=http://172.31.47.241:7890
      - HTTPS_PROXY=http://172.31.47.241:7890
